name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Read current version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Determine bump type from last commit
        id: bump
        run: |
          LAST_COMMIT=$(git log -1 --pretty=%B)

          if echo "$LAST_COMMIT" | grep -q "BREAKING CHANGE"; then
            echo "bump=major" >> "$GITHUB_OUTPUT"
          elif echo "$LAST_COMMIT" | grep -q "^feat:"; then
            echo "bump=minor" >> "$GITHUB_OUTPUT"
          elif echo "$LAST_COMMIT" | grep -q "^fix:"; then
            echo "bump=patch" >> "$GITHUB_OUTPUT"
          else
            echo "bump=none" >> "$GITHUB_OUTPUT"
          fi

      - name: Bump semantic version
        id: newver
        run: |
          OLD=${{ steps.version.outputs.version }}

          MAJOR=$(echo "$OLD" | cut -d. -f1)
          MINOR=$(echo "$OLD" | cut -d. -f2)
          PATCH=$(echo "$OLD" | cut -d. -f3)

          case "${{ steps.bump.outputs.bump }}" in
            major)
              NEW="$((MAJOR+1)).0.0"
              ;;
            minor)
              NEW="$MAJOR.$((MINOR+1)).0"
              ;;
            patch)
              NEW="$MAJOR.$MINOR.$((PATCH+1))"
              ;;
            none)
              NEW="$OLD"
              ;;
          esac

          echo "$NEW" > version.txt
          echo "newversion=$NEW" >> "$GITHUB_OUTPUT"

      - name: Commit version bump
        if: steps.bump.outputs.bump != 'none'
        run: |
          git add version.txt
          git commit -m "chore: release v${{ steps.newver.outputs.newversion }}" || echo "No changes to commit"
          git tag -a "v${{ steps.newver.outputs.newversion }}" -m "Release v${{ steps.newver.outputs.newversion }}"
          git push --follow-tags

      - name: Generate changelog content
        if: steps.bump.outputs.bump != 'none'
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: .github/changelog-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        if: steps.bump.outputs.bump != 'none'
        run: |
          NEW_VER="v${{ steps.newver.outputs.newversion }}"
          DATE=$(date +'%Y-%m-%d')

          echo "## ${NEW_VER} - ${DATE}" > /tmp/changelog_section.md
          echo "" >> /tmp/changelog_section.md
          echo "${{ steps.changelog.outputs.changelog }}" >> /tmp/changelog_section.md
          echo "" >> /tmp/changelog_section.md

          if [[ -f CHANGELOG.md ]]; then
            cat /tmp/changelog_section.md CHANGELOG.md > /tmp/CHANGELOG.new
            mv /tmp/CHANGELOG.new CHANGELOG.md
          else
            mv /tmp/changelog_section.md CHANGELOG.md
          fi

          git add CHANGELOG.md
          git commit -m "docs: update changelog for ${NEW_VER}" || echo "No changelog changes"
          git push

      - name: Build Docker image
        if: steps.bump.outputs.bump != 'none'
        run: |
          VERSION=${{ steps.newver.outputs.newversion }}
          docker build -t uninspiredenvy/unraid-backup-tool:${VERSION} -t uninspiredenvy/unraid-backup-tool:latest .

      - name: Login to Docker Hub
        if: steps.bump.outputs.bump != 'none'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: steps.bump.outputs.bump != 'none'
        run: |
          VERSION=${{ steps.newver.outputs.newversion }}
          docker push uninspiredenvy/unraid-backup-tool:${VERSION}
          docker push uninspiredenvy/unraid-backup-tool:latest

      - name: Create GitHub Release
        if: steps.bump.outputs.bump != 'none'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.newver.outputs.newversion }}
          name: Release v${{ steps.newver.outputs.newversion }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

